<?php
/**
 * @file
 * Code for the CA Before and After feature.
 */

include_once 'ca_before_and_after.features.inc';

/**
 * Implements hook_menu()
 */
function ca_before_and_after_menu() {
  $items['admin/config/worx_features/before_and_after'] = array(
    'title' => 'Before and After Configuration',
    'description' => 'Override settings for ca_before_and_after',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_before_and_after_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_before_and_after.admin.inc',
    'file path' => drupal_get_path('module', 'ca_before_and_after'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/worx_features/before_and_after/general'] = array(
    'title' => 'General Settings',
    'description' => 'Override settings for ca_before_and_after',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_before_and_after_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_before_and_after.admin.inc',
    'file path' => drupal_get_path('module', 'ca_before_and_after'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * implements hook_menu_alter().
 */
function ca_before_and_after_menu_alter(&$items) {
  $items['results']['title'] = variable_get('ca_before_and_after_menu_title', 'Results');
}

/**
 * Implements hook_views_pre_render().
 */
function ca_before_and_after_views_pre_view(&$view, &$display_id, &$args) {
  if ($display_id == 'ca_event_list_1') {
    $view->set_items_per_page(variable_get('ca_before_and_after_list_count', 5));
  }
  elseif ($display_id == 'ca_event_block_1') {
    $view->set_items_per_page(variable_get('ca_before_and_after_block_count', 1));
  }
}

/**
* Implementation of hook_ctools_plugin_directory()
*/
function ca_before_and_after_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;;
  }
}

